# Generated by Django 4.2.16 on 2024-11-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnableDataCollection', models.BooleanField(default=True)),
                ('ActivityTracking', models.BooleanField(default=True)),
                ('VoiceDataCollection', models.BooleanField(default=True)),
                ('LocationTracking', models.BooleanField(default=True)),
                ('ShareDataWithThirdParties', models.BooleanField(default=True)),
                ('AllowUsageTracking', models.BooleanField(default=True)),
                ('DataEncryption', models.BooleanField(default=True)),
                ('StorePersonalUsageData', models.BooleanField(default=True)),
                ('StorePurchaseHistory', models.BooleanField(default=True)),
                ('AllowDataCollectionForCrossDevice', models.BooleanField(default=True)),
            ],
        ),
    ]
