# Generated by Django 4.2.16 on 2024-11-19 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BojanglesSecurity', '0002_device_remove_privacysettings_dataencryption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacysettings',
            name='device',
        ),
    ]
