# Generated by Django 4.2.16 on 2024-11-19 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BojanglesSecurity', '0003_remove_privacysettings_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacysettings',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='device', to='BojanglesSecurity.device'),
            preserve_default=False,
        ),
    ]
